export const GET_PROFILE = 'GET_PROFILE ';
export const GET_PROFILES = 'GET_PROFILES ';
export const CURRENT_PROFILE = 'CURRENT_PROFILE ';
export const PROFILE_ERROR = 'PROFILE_ERROR ';
export const CLEAR_PROFILE = 'CLEAR_PROFILE ';
export const CLEAR_PROFILES = 'CLEAR_PROFILES ';
export const CLEAR_CURRENT_PROFILE = 'CLEARCURRENT_PROFILE ';
